[book]
title = "Vulnera Documentation"
authors = ["Khaled Mahmoud", "Abd El-Rahman Mossad", "Amr Medhat"]
description = "Documentation for Vulnera - High-Performance Vulnerability Analysis Platform"
src = "src"
language = "en"

[rust]
edition = "2024"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/k5602/Vulnera"
edit-url-template = "https://github.com/k5602/Vulnera/edit/main/docs/{path}"
site-url = "/Vulnera/"
no-section-label = false

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
copy-js = true

[output.html.playground]
editable = false
copyable = true
copy-js = true
